<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SEZT1FF266MANGO" ignored="0" name="EmployeeRestAPITest" tests="37" failures="6" timestamp="24 Sep 2020 12:41:28 GMT" time="21.423" errors="0">
  <testcase name="@BeforeClass deleteEmployees" time="1.199" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.employeeapi.testcases.TC005_Delete_Employee_Record.deleteEmployees(TC005_Delete_Employee_Record.java:29)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 30 more
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass deleteEmployees -->
  <testcase name="@AfterClass tearDown" time="0.0" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="checkContentEncoding" time="0.004" classname="com.employeeapi.testcases.TC001_Get_All_Employees"/>
  <testcase name="checkContentLength" time="0.001" classname="com.employeeapi.testcases.TC001_Get_All_Employees"/>
  <testcase name="checkContentType" time="0.0" classname="com.employeeapi.testcases.TC001_Get_All_Employees"/>
  <testcase name="checkCookies" time="0.001" classname="com.employeeapi.testcases.TC001_Get_All_Employees">
    <failure type="java.lang.AssertionError" message="expected [askldknklaskfn] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [askldknklaskfn] but found [null]
at com.employeeapi.testcases.TC001_Get_All_Employees.checkCookies(TC001_Get_All_Employees.java:119)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkCookies -->
  <testcase name="checkResponseBody" time="0.011" classname="com.employeeapi.testcases.TC001_Get_All_Employees"/>
  <testcase name="checkResponseTime" time="0.0" classname="com.employeeapi.testcases.TC001_Get_All_Employees">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testcases.TC001_Get_All_Employees.checkResponseTime(TC001_Get_All_Employees.java:55)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseTime -->
  <testcase name="checkServerType" time="0.001" classname="com.employeeapi.testcases.TC001_Get_All_Employees"/>
  <testcase name="checkStatusCode" time="0.0" classname="com.employeeapi.testcases.TC001_Get_All_Employees"/>
  <testcase name="checkStatusLine" time="0.001" classname="com.employeeapi.testcases.TC001_Get_All_Employees"/>
  <testcase name="checkContentLength" time="0.001" classname="com.employeeapi.testcases.TC002_Get_Single_Employee_Record">
    <failure type="java.lang.NumberFormatException" message="null">
      <![CDATA[java.lang.NumberFormatException: null
at java.lang.Integer.parseInt(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at com.employeeapi.testcases.TC002_Get_Single_Employee_Record.checkContentLength(TC002_Get_Single_Employee_Record.java:85)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- checkContentLength -->
  <testcase name="checkContentType" time="0.001" classname="com.employeeapi.testcases.TC002_Get_Single_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapi.testcases.TC002_Get_Single_Employee_Record.checkContentType(TC002_Get_Single_Employee_Record.java:67)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResponseBody" time="0.005" classname="com.employeeapi.testcases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkResponseTime" time="0.001" classname="com.employeeapi.testcases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkServerType" time="0.001" classname="com.employeeapi.testcases.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employeeapi.testcases.TC002_Get_Single_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testcases.TC002_Get_Single_Employee_Record.checkStatusCode(TC002_Get_Single_Employee_Record.java:40)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkStatusLine" time="0.001" classname="com.employeeapi.testcases.TC002_Get_Single_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testcases.TC002_Get_Single_Employee_Record.checkStatusLine(TC002_Get_Single_Employee_Record.java:59)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase name="checkContentLength" time="0.003" classname="com.employeeapi.testcases.TC003_Post_Employee_Record"/>
  <testcase name="checkContentType" time="0.001" classname="com.employeeapi.testcases.TC003_Post_Employee_Record"/>
  <testcase name="checkResponseBody" time="0.001" classname="com.employeeapi.testcases.TC003_Post_Employee_Record"/>
  <testcase name="checkResponseTime" time="0.0" classname="com.employeeapi.testcases.TC003_Post_Employee_Record"/>
  <testcase name="checkServerType" time="0.0" classname="com.employeeapi.testcases.TC003_Post_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.0" classname="com.employeeapi.testcases.TC003_Post_Employee_Record"/>
  <testcase name="checkStatusLine" time="0.0" classname="com.employeeapi.testcases.TC003_Post_Employee_Record"/>
  <testcase name="checkContentLength" time="0.001" classname="com.employeeapi.testcases.TC004_Put_Employee_Record"/>
  <testcase name="checkContentType" time="0.001" classname="com.employeeapi.testcases.TC004_Put_Employee_Record"/>
  <testcase name="checkResponseBody" time="0.0" classname="com.employeeapi.testcases.TC004_Put_Employee_Record"/>
  <testcase name="checkResponseTime" time="0.0" classname="com.employeeapi.testcases.TC004_Put_Employee_Record"/>
  <testcase name="checkServerType" time="0.0" classname="com.employeeapi.testcases.TC004_Put_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.0" classname="com.employeeapi.testcases.TC004_Put_Employee_Record"/>
  <testcase name="checkStatusLine" time="0.001" classname="com.employeeapi.testcases.TC004_Put_Employee_Record"/>
  <testcase name="checkContentLength" time="0.0" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkContentLength -->
  <testcase name="checkContentType" time="0.0" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResponseBody" time="0.0" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkResponseTime" time="0.0" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkResponseTime -->
  <testcase name="checkServerType" time="0.0" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkServerType -->
  <testcase name="checkStatusCode" time="0.0" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkStatusLine" time="0.0" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkStatusLine -->
</testsuite> <!-- EmployeeRestAPITest -->
